# Generated by Django 2.2.4 on 2021-05-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ninjas',
            new_name='Ninja',
        ),
    ]
